kind: Secret
apiVersion: v1
metadata:
  name: airflow-secrets
  namespace: ${namespace}
data:
  # example: postgres://airflow:airflow@postgres:5432/airflow
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: 
type: Opaque