kind: Secret
apiVersion: v1
metadata:
  name: airflow-secrets
  namespace: ${namespace}
data:
  # example: postgres+psycopg2://airflow:airflow@postgres:5432/airflow in base64
  AIRFLOW__CORE__SQL_ALCHEMY_CONN:
type: Opaque